### ISSUE TITLE
Some enhancements for the ingest and the dashboard

### ISSUE THREAD

**Issue by 111andre111** [andrewkroh/go-ingest-node-metrics#1]
First of all thank you for this extremely helpful tool.

However I would propose some of the following adjustments.

I have observed the same like in your screenshot.
https://github.com/andrewkroh/go-ingest-node-metrics/blob/main/docs/ingest-node-pipeline-dashboard.png
1. Please have a look at the conditionals like e.g. the cisco asa pipeline this if condition if in reality based on a date processor with names like `7_conditional` or `181_conditional` which don't really help what exact processor equivalent in the pipeline this is about:
https://github.com/elastic/beats/blob/v7.13.3/x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml#L73-L104
and looking to the elasticsearch `/_ingest/pipeline` query the resulting equivalent JSON looks like that:
![2021-07-19 20_30_34-Lister (jsonviewer) -  D__download_elastic_rally_sdh_998_track_pipeline_filebeat](https://user-images.githubusercontent.com/48132449/126209733-f12da51f-f6e3-4db3-8120-316f1aeebadd.png)
However looking to the relevant part of the `/_nodes/stats` query the date processor is not really reflected as of the key, but the other 2 show the relevant used processor and not only the type as conditional itself.
![2021-07-19 20_43_46-Lister (jsonviewer) -  D__download_elastic_rally_sdh_998_track_nodes_stats_20210](https://user-images.githubusercontent.com/48132449/126211045-c73fb093-e327-45c4-badd-7ff9ce7588e2.png)
So it would be helpful a lot if one could ingest the pipeline stats key itself to identify better, what exact processor inside the pipeline this is talking about, and then reflect that one in the dashboard pie.

2. Another enhancement would be to add column `pipeline` to the `Processor Stats Table` in case multiple pipelines are used:
![2021-07-19 20_35_54-2021-07-18 00_01_49-Ingest Node Pipeline Metrics - Elastic png ‎- Fotos](https://user-images.githubusercontent.com/48132449/126210106-160f1a1d-7b76-452d-baa6-e163ad86ec90.png)

3. Finally it would be really cool if there could be configured a cluster with https (maybe with ignored certificated validation) but as of now it's only possibly to ingest into an elasticsearch cluster with http.

**Comment by andrewkroh** [comment]
> Finally it would be really cool if there could be configured a cluster with https (maybe with ignored certificated validation) but as of now it's only possibly to ingest into an elasticsearch cluster with http.

The `--es-url` will accept an `https://` URL, but the endpoint must have valid certs since there is no way to ignore validation errors.

**Comment by 111andre111** [comment]
Ah, ok perfect. I was even not aware of the helping parameters.
BTW it seems that normally there is a method to do this for self signed certificates to offer at least certificates:
https://pkg.go.dev/crypto/tls#Client

however I immediately managed to do this part testing this parameter:
```
>go-ingest-node-metrics -h
Usage:   pipeline-stats [flags] node-stats-json-file
  -api-key string          Elasticsearch API key
  -es-url string           Elasticsearch URL (default "http://localhost:9200")
  -import-id string        import ID (default "1626724703319581600")
  -index string            name of index to create (default "pipeline-stats")
  -p string                Elasticsearch password
  -u string                Elasticsearch username
>go-ingest-node-metrics -u elastic -p <pw> -es-url https://localhost:9200 nodes_stats.json
  Creating new "pipeline-stats" index.
  Sucessfuly indexed [14448] documents.
# and still managed to import directly to kibana the dashboard, just for documentation:
>curl -k -uelastic:<pw> -XPOST "https://localhost:5601/api/saved_objects/_import?overwrite=true" -H "kbn-version: 7.13.2" --form file=@dashboard.ndjson
```
So seems like point 3 is immediately solved now.

So still curious about 1. and 2. Thank you.

**Comment by andrewkroh** [comment]
So for (1) are you proposing that it would read both the node stats and the pipeline definition in order to enrich the data with a better description and/or `processor_name`?

And for (2) that makes sense and would be easy to add.

**Comment by 111andre111** [comment]
For (1) just let me add another screenshot, I think ingesting the missing ones would be enough:

![2021-07-22 21_40_29-Some enhancements for the ingest and the dashboard · Issue #1 · andrewkroh_go-in](https://user-images.githubusercontent.com/48132449/126700406-68282c0d-f70e-442f-9c78-3e9495e6bd9a.png)

**Comment by andrewkroh** [comment]
Implemented by https://github.com/andrewkroh/go-ingest-node-metrics/commit/b5aa4514d8014da860b1c529f4748791feea1ebc. See the commit for a full description of the changes.

**Comment by 111andre111** [comment]
Thank you, however I thought you would ingest the keys like shown in the former screenshot of the simple json without the need of an extra `-pipelines-json` parameter?
Because sometimes you will have a pipeline that basically works with multiple pipelines included. So how would you do that then?

Additionally I didn't get it working with `-pipelines-json`.
With having all pipelines in pipeline.json I get the error
```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.denormalizeIngestStats(0xc000006048, 0xc000305950, 0xc000305950, 0x0, 0x0)
        .../go/src/github.com/andrewkroh/go-ingest-node-metrics/pipline.stats.go:266 +0xc59
main.main()
        .../go/src/github.com/andrewkroh/go-ingest-node-metrics/pipline.stats.go:206 +0x14a
```
and with having the direct pipeline in the file I get error:
```
2021/10/02 22:13:28 json: cannot unmarshal string into Go value of type main.IngestPipeline
```

Finally you are using embed which is only possible to use since go 1.16 https://tip.golang.org/doc/go1.16#library-embed, otherwise one will result in error:
```
pipline.stats.go:23:2: package embed is not in GOROOT (.../.gvm/versions/go1.14.7/src/embed)
```
when trying to execute
```
go get github.com/andrewkroh/go-ingest-node-metrics
```

**Comment by andrewkroh** [comment]
> I thought you would ingest the keys like shown in the former screenshot of the simple json without the need of an extra -pipelines-json parameter?

It seems I did not understand the information being conveyed in the screenshot. I thought the problem was that for processors with `if` conditions that it was showing the processor name as `7_conditional` and the desired valued was `7_date`. I didn't see anywhere in the stats that indicated the underlying processor was `date` so I got it from the pipeline definition.

**Comment by andrewkroh** [comment]
> With having all pipelines in pipeline.json I get the error

> panic: runtime error: index out of range [1] with length 1

Is is possible that the stats don't match with what you have in your pipelines JSON file? Are the two out of sync? I tested with the output of a diagnostic dump and didn't encounter that problem, but it might just have been that this one diagnostic didn't have that issue. If you can continue to reproduce then I can examine the content of the two files to see what went wrong.

**Comment by andrewkroh** [comment]
> and with having the direct pipeline in the file I get error:

> 2021/10/02 22:13:28 json: cannot unmarshal string into Go value of type main.IngestPipeline

It only works if the format of the pipelines-json file is as given from `GET _ingest/pipeline`.

**Comment by andrewkroh** [comment]
> Finally you are using embed which is only possible to use since go 1.16

Yes. It requires Go 1.16.

**Comment by 111andre111** [comment]
> It seems I did not understand the information being conveyed in the screenshot. I thought the problem was that for processors with if conditions that it was showing the processor name as 7_conditional and the desired valued was 7_date.

Ok, what I meant is to have the information ingested into elasticsearch like the main keys looking back to the screenshots that are basically marked as `missing` in the screenshot.

So for the screenshot documents that would be having an additional field like this for every sub structure:
```
compound:CompoundProcessor-null-null
sort
sort
```
At the moment field `processor_name` seems to be a combination of the count of the type progressing over the pipeline.
https://github.com/andrewkroh/go-ingest-node-metrics/blob/4dc0bd8e16ac7a7af414caa0c6826273813cc551/pipline.stats.go#L279

So having this key in addition would make the name much more comprehensive like e.g. from former

```
1_conditional
2_conditional
3_conditional
```
to
```
1_conditional_compound-CompoundProcessor-null-null
2_conditional_set
3_conditional_set
```
seems to be much more informative for me. Hope that makes now a better sense of what I mean.

> It only works if the format of the pipelines-json file is as given from GET _ingest/pipeline.

I went ahead and checked again and now it was working, but still with the downside that this works only if I have a `GET _ingest/pipeline` file, which might not always be the case. With the former mentioned approach that would still be readable without a pipeline.json file.

**Comment by andrewkroh** [comment]
I added a `stat_name` field that contains the data that was labeled as missing in a171aca8c4c536da5983db6227beedb590362888.

So right now when ingesting with `-pipelines-json` you will get a `processor_name` that's composed as:

`{{index}}_{{real processor type}}_{{optional tag}`

That would be `1_script_remove_nulls` or `1_script` if there were no `tag`. There is field indicating if the processor is `conditional` and a `stat_name` containing the name from the _nodes/stats (e.g. `compound-CompoundProcessor-null-null`).

```json
{
  "import_id": "1633382126520459000",
  "metric_type": "processor",
  "node": "abcdefghijklmnopqrstuvwxyz",
  "pipeline": "filebeat-7.12.0-crowdstrike-falcon-pipeline",
  "count": 0,
  "current": 0,
  "failed": 0,
  "time_in_millis": 0,
  "stat_name": "compound:CompoundProcessor-null",
  "processor_index": 31,
  "processor_type": "set",
  "processor_name": "31_set",
  "pipeline_stats": {
    "count": 0,
    "current": 0,
    "failed": 0,
    "time_in_millis": 0
  },
  "calculated": {
    "execution_time_avg_ns": 0,
    "time_pct": 0,
    "failed_pct": 0
  },
  "definition": "{\n          \"field\" : \"user.email\",\n          \"value\" : \"{{user.name}}\",\n          \"ignore_empty_value\" : true,\n          \"ignore_failure\" : true,\n          \"if\" : \"ctx?.user?.name != null && /@/.split(ctx.user.name).length == 2\"\n        }",
  "conditional": true
}
```

**Comment by 111andre111** [comment]
That's extreemely nice. That's working having the field now for searches. Thank you for this enhancement. Even when ingested with out -pipelines parameter having the field allows double checking the matching processor. 👍
